common/models/Task.php
<?php

namespace common\models;

use yii\data\ActiveDataProvider;
use yii\web\ErrorException;

/**
 * This is the model class for table "Task".
 *
 * @property integer $id
 * @property integer $projectId
 * @property integer $projectBuildId
 * @property integer $assigneeId
 * @property integer $typeId
 * @property integer $statusId
 * @property string $name
 * @property string $description
 * @property integer $priorityId
 * @property string $startDate
 * @property string $endDate
 * @property integer $authorId
 * @property integer $modifierId
 * @property string $createTime
 * @property string $updateTime
 *
 * @property string $priority
 * @property Taskstatus $status
 * @property Project $project
 * @property ProjectBuild $projectBuild
 * @property User $assignee
 * @property string $type
 * @property string $status
 * @property TaskAttachment[] $attachments
 * @property TaskComment[] $comments
 * @property User $author
 * @property User $modifier
 * @property boolean $isOvertime write-only attribute
 */
class Task extends \yii\db\ActiveRecord
{
	public $isOvertime = false;
	
	/**
	 * @inheritdoc
	 */
	public function __construct($config = [])
	{
		parent::__construct($config);
		$today = date('Y-m-d');
		$this->startDate = $today;
		$this->endDate = $today;
	}
	
	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'Task';
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['projectBuildId', 'assigneeId', 'typeId', 'name', 'startDate', 'endDate', 'authorId', 'modifierId'], 'required'],
			[['projectBuildId', 'assigneeId', 'typeId', 'priorityId', 'statusId', 'authorId', 'modifierId'], 'integer'],
			[['startDate', 'endDate', 'createTime', 'updateTime'], 'safe'],
			[['name'], 'string', 'max' => 255],
			[['description'], 'string'],
			[['isOvertime'], 'boolean'],
			
			['endDate', 'compare', 'compareAttribute' => 'startDate', 'operator' => '>=',
				'message'=>'{attribute} must be greater than or equal {compareValue}.'
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'projectBuildId' => 'Build',
			'assigneeId' => 'Assignee',
			'typeId' => 'Type',
			'statusId' => 'Status',
			'name' => 'Name',
			'description' => 'Description',
			'startDate' => 'Start',
			'endDate' => 'End',
			'priorityId' => 'Priority',
			'authorId' => 'Author',
			'modifierId' => 'By',
			'createTime' => 'Created',
			'updateTime' => 'Updated',
			'isOvertime' => 'Overtime',
		];
	}
	
	/**
	 * Fill Project.authorId before call validate.
	 * @inheritdoc
	 */
	public function beforeValidate()
	{
		if ($this->isNewRecord) {
			$this->authorId = $this->modifierId = \Yii::$app->user->getId();
			$this->statusId = TaskStatus::STATUS_NEW;
		}
		return parent::beforeValidate();
	}
	
	/**
	 * return string
	 */
	public function getPriority()
	{
		return Priority::getName($this->priorityId);
	}
	
	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getProject()
	{
		return $this->hasOne(Project::className(), ['id' => 'projectId']);
	}
	
	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getProjectBuild()
	{
		return $this->hasOne(ProjectBuild::className(), ['id' => 'projectBuildId']);
	}
	
	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getAssignee()
	{
		return $this->hasOne(User::className(), ['id' => 'assigneeId']);
	}
	
	/**
	 * @return string
	 */
	public function getType()
	{
		return TaskType::getName($this->typeId);
	}
	
	/**
	 * @return string	html span
	 */
	public function getStatus()
	{
		return TaskStatus::getName($this->statusId);
	}
	
	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getAttachments()
	{
		return $this->hasMany(TaskAttachment::className(), ['taskId' => 'id']);
	}
	
	/**
	 * @return \yii\data\ActiveDataProvider
	 */
	public function getComments()
	{
		$query = TaskComment::find()
			->where(['taskId' => $this->id])
			->orderBy('id DESC');
		$dataProvider = new ActiveDataProvider([
			'query' => $query,
			'pagination' => false,
		]);
		
		return $dataProvider;
	}
	
	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getAuthor()
	{
		return $this->hasOne(User::className(), ['id' => 'authorId']);
	}
	
	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getModifier()
	{
		return $this->hasOne(User::className(), ['id' => 'modifierId']);
	}
	
	/**
	 * @return \common\models\Task[]
	 */
	public function getAssignedTasks($userId, $filter)
	{
		$query = static::find()
		->innerJoin('ProjectAssignment', 'ProjectAssignment.id = Task.projectBuildId')
		->innerJoin('ProjectMember', 'ProjectMember.id = ProjectAssignment.projectMemberId')
		->innerJoin('Member', 'Member.id = ProjectMember.memberId AND Member.id = :id', [':id' => $userId]);
		
		$models = $query->all();
		return $models;
	}
	
	public static function getSummary($projectId, $typeId, $endDate)
	{
		$summary = [
			'date' => $endDate,
			'total' => static::find()
				->select('id')
				->where(['projectId' => $projectId, 'typeId' => $typeId, 'endDate' => $endDate])
				->count(),
			'closed' => static::find()
				->select('id')
				->where(['projectId' => $projectId, 'typeId' => $typeId, 'endDate' => $endDate])
				->andWhere(['statusId' => [
					TaskStatus::STATUS_RESOLVED, 
					TaskStatus::STATUS_DUPLICATE,
					TaskStatus::STATUS_INVALID,
					TaskStatus::STATUS_WONT_FIX,
					TaskStatus::STATUS_SPAM,
				]])
				->count(),
		];
		
		// \yii\helpers\VarDumper::dump($summary, 10, true); exit();
		return $summary;
	}
}

common/models/TaskType.php
<?php

namespace common\models;

/**
 * Task types, instead of "TaskType" table.
 */
class TaskType
{
	const TYPE_TARGET 					= 1;
	const TYPE_ISSUE 					= 2;
	const TYPE_FEEDBACK					= 3;
	const TYPE_REQUEST					= 4;
	const TYPE_MILESTONE				= 5;
	const TYPE_MICRO_PLANNING			= 6;
	
	private static $TYPES = [
		self::TYPE_TARGET => 'target',
		self::TYPE_ISSUE => 'issue',
		self::TYPE_FEEDBACK => 'feedback',
		self::TYPE_REQUEST => 'request',
		self::TYPE_MILESTONE => 'milestone',
		self::TYPE_MICRO_PLANNING => 'micro planning',
	];
	
	public static function getName($id)
	{
		return static::$TYPES[$id];
	}
	
	public static function getArray()
	{
		return static::$TYPES;
	}
}

frontend/controllers/TaskController.php
<?php

namespace frontend\controllers;

//use common\models\AccessRule;
use common\models\Overtime;
use common\models\Project;
use common\models\Task;
use common\models\TaskAttachment;
use common\models\TaskComment;
use common\models\TaskStatus;
use common\models\TaskType;
use common\models\Role;
use common\models\search\TaskSearch;
use frontend\models\TaskEmail;
use yii\helpers\BaseJson;
use yii\web\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use Yii;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
//				'ruleConfig' => [
//					'class' => AccessRule::className()
//				],
				'rules' => [
					[
						'allow' => true,
						'actions' => ['index', 'view', 'create', 'change', 'update', 'suggest'],
						'roles' => ['@'],
					],
					[
						'allow' => true,
						'actions' => ['delete', 'mail'],
						'roles' => [Role::ROLE_MANAGER],
					],
				],
			],
		];
	}

	/**
	 * Lists Task models.
	 * @param integer $projectId		project id, require.
	 * @param integer $typeId			task type id, require.
	 * @return mixed
	 */
	public function actionIndex($projectId, $typeId)
	{
		$searchModel = new TaskSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
		
		$filter = Yii::$app->request->get('filter');
		$project = Project::find($projectId);
		
		return $this->render('index', [
			'project' => $project,
			'dataProvider' => $dataProvider,
			'typeId' => $typeId,
			'filter' => $filter,
		]);
	}

	/**
	 * Displays a single Task model.
	 * @param string $id
	 * @return mixed
	 */
	public function actionView($id)
	{
		$model = $this->findModel($id);
		return $this->render('view', [
			'model' => $model,
		]);
	}

	/**
	 * Creates a new Task model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate($projectId, $typeId, $projectBuildId = 0, $assigneeId = 0)
	{
		$model = new Task();
		if ($model->load(Yii::$app->request->post())) {
			// POST -> create one task or many tasks
			$model->projectId = $projectId;
			$model->typeId = $typeId;
			if ($projectBuildId> 0) {
				$model->projectBuildId = $projectBuildId;
			}
			if ($assigneeId> 0) {
				$model->assigneeId = $assigneeId;
			}
			$model->description = Yii::$app->getRequest()->post('Task')['description'];
			// \yii\helpers\VarDumper::dump($model, 10, true);exit();
			
			if ($model->save()) {
				//Attachments
				$shareAttachment = new TaskAttachment();
				if ($shareAttachment->load(Yii::$app->request->post())) {
					$uploadFile = UploadedFile::getInstance($shareAttachment, 'baseName');
					if ($uploadFile != null && $uploadFile->name != null) {
						$attachment = new TaskAttachment();
						$attachment->generateValues($model, $uploadFile);
						$attachment->save();
					}
				}
				
				//Overtime
				if ($model->isOvertime) {
					$overtime = new Overtime();
					if ($overtime->load(Yii::$app->request->post())) {
						$overtime->projectId = $model->projectId;
						$overtime->taskId = $model->id;
						$overtime->save();
					}
				}
			}
			
			Yii::$app->session->setFlash('info', "A new task has been added successful.");
			if ($projectBuildId != 0) {
				return $this->redirect(['project-build/view', 'id' => $projectBuildId]);
			} else {
				return $this->redirect(['view', 'id' => $model->id]);
			}
		}
		else
		{
			// Show input form
			$model = new Task();
			$model->projectId = $projectId;
			$model->typeId = $typeId;
			$model->assigneeId = Yii::$app->user->identity->id;

			return $this->render('create', [
				'model' => $model,
				'projectBuildId' => $projectBuildId,
				'assigneeId' => $assigneeId,
			]);
		}
	}
	
	/**
	 * Updates an existing Task model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param string $id
	 * @return mixed
	 */
	public function actionUpdate($id)
	{
		$model = $this->findModel($id);
		
		if ($model->load(Yii::$app->request->post())) {
			// \yii\helpers\VarDumper::dump($model, 10, true); exit();
			// Check dirty attributes (before call Task::save() method) & save a comment for changes
			$comment = new TaskComment();
			$comment->load(Yii::$app->request->post());
			$isChanged = $comment->generateValues($model);	//keep logic since use Select2 with multi selections
			
			if ($isChanged && $model->save()) {
				// \yii\helpers\VarDumper::dump($this, 10, true); exit();
				$comment->save();
				
				//Attachments
				$attachment = new TaskAttachment();
				if ($attachment->load(Yii::$app->request->post())) {
					$uploadFile = UploadedFile::getInstance($attachment, 'baseName');
					// \yii\helpers\VarDumper::dump($uploadFile, 10, true); exit();
					if ($uploadFile != null && $uploadFile->name != null) {
						$attachment->generateValues($model, $uploadFile);
						$attachment->save();
					}
				}
				
				Yii::$app->session->setFlash('success', "This task has been updated.");
			}
			
			//Overtime
			if ($model->isOvertime) {
				$overtime = new Overtime();
				if ($overtime->load(Yii::$app->request->post())) {
					$overtime->projectId = $model->projectId;
					$overtime->taskId = $model->id;
					$overtime->save();
				}
				
				Yii::$app->session->setFlash('success', "Overtime has been recorded.");
			}
			
			return $this->redirect(['view', 'id' => $id]);
		} else {
			return $this->render('update', [
				'model' => $model,
			]);
		}
	}

	/**
	 * Deletes an existing Task model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $projectId		 	project id
	 * @param integer $id 			task id
	 * @return mixed
	 */
	public function actionDelete($id)
	{
		$model = $this->findModel($id);
		if (Yii::$app->getRequest()->getIsPost()) {
			$model->delete();
			Yii::$app->session->setFlash('info', ucfirst(TaskType::getName($model->typeId)) . ' has been deleteted');
			return $this->redirect(['task/index', 'projectId' => $model->projectId, 'typeId' => $model->typeId, 'status' => TaskStatus::STATUS_UNRESOLVED]);
		} else {
			return $this->renderAjax('delete', ['model' => $model]);
		}
	}
	
	/**
	 * Send an email to all members of a project.
	 * AJAX
	 * @param integer $projectId		project id, require.
	 * @param integer $typeId			task type id, require.
	 * @return mixed
	 */
	public function actionMail($projectId, $typeId)
	{
		$project = Project::find($projectId);
		$model = new TaskEmail($project, $typeId);
		
		if ($model->load(Yii::$app->request->post())) {
			$searchModel = new TaskSearch();
			$dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
			
			$model->generateMessage();
			if (Yii::$app->mail->compose('task', ['model' => $model, 'dataProvider' => $dataProvider])
				->setFrom([Yii::$app->params['supportEmail'] => 'Ptracking'])
				->setTo($model->to)
				->setCc($model->cc)
				->setSubject($model->subject)
				->send()
			) {
				Yii::$app->session->setFlash('info', "The email has been sent successful.");
			} else {
				Yii::$app->session->setFlash('error', "The email can not be sent!");
			}
			
			$params = Yii::$app->getRequest()->getQueryParams();
			$url[] = 'index';				// Can't use ArrayHelper::merge() method
			foreach ($params as $key => $value) {
				$url[$key] = $value;
			}
			
			return $this->redirect($url);
		} else {
			return $this->renderAjax('mail', [
				'model' => $model,
				'typeId' => $typeId
			]);
		}
	}

	public function actionSuggest($projectId, $name)
	{
		$models = Task::find()
			->select('name')
			->where(['projectId' => $projectId])
			->andWhere(['like', 'name', $name])
			->limit(10)
			->column();
			
		echo BaseJson::encode($models);
	}
	
	/**
	 * Finds the Task model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param string $id
	 * @return Task the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = Task::find($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}
}

frontend/views/task/_form.php
<?php

use common\models\Priority;
use common\models\ProjectBuild;
use common\models\ProjectMember;
use common\models\TaskAttachment;
use common\models\TaskType;
use ez\widgets\SwitchButton;
use kartik\markdown\MarkdownEditor;
use kartik\widgets\FileInput;
use kartik\widgets\Select2;
use kartik\widgets\Typeahead;
use kartik\widgets\DatePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var yii\widgets\ActiveForm $form
 * @var common\models\Task $model
 * @var integer $projectBuildId
 * @var integer $assigneeId
 * @var string $header
 */
?>

<?php
$builds = ProjectBuild::getArrayByProjectId($model->project->id);
$members = ProjectMember::getArrayByProjectId($model->project->id);
$attachment = new TaskAttachment();
?>

<?= $this->render('//layouts/_navbar', ['project' => $model->project, 'controller' => 'task', 'typeId' => $model->typeId]) ?>

<?php $form = ActiveForm::begin([
    'id' => 'task-form',
    'options' => [
    	'class' => 'form-horizontal',
    	'enctype' => 'multipart/form-data'
    ],
    'fieldConfig' => [
		'template' => "{label}\n<div class=\"col-lg-8\">{input}</div>\n<div class=\"col-lg-8 col-md-offset-2\">{error}</div>",
		'labelOptions' => ['class' => 'col-lg-2 control-label'],
    ],
]); ?>

<div class="panel panel-default">
	<div class="panel-heading clearfix">
		<strong><?= $header ?></strong>
	</div>
	<div class="panel-body">
		<?= $form->field($model, 'name')->widget(Typeahead::className(), [
			'options' => [
				'placeholder' => 'Type then pick one of suggestions...'
			],
			'dataset' => [
				[
					'remote' => Html::url(['task/suggest', 'projectId' => 1]) . '&name=%QUERY',
					'limit' => 10
				]
			]
		]) ?>
		
		<?= $form->field($model, 'description')->widget(MarkdownEditor::classname(), [
			'height' => 100,
			'encodeLabels' => true,
			'toolbar' => [
				[
					'buttons' => [
						MarkdownEditor::BTN_BOLD => ['icon' => 'bold', 'title' => 'Bold'],
						MarkdownEditor::BTN_ITALIC => ['icon' => 'italic', 'title' => 'Italic'],
					],
				],
				[
					'buttons' => [
						MarkdownEditor::BTN_LINK => ['icon' => 'link', 'title' => 'URL/Link'],
						MarkdownEditor::BTN_IMAGE => ['icon' => 'picture', 'title' => 'Image'],
					],
				],
				[
					'buttons' => [
						MarkdownEditor::BTN_INDENT_L => ['icon' => 'indent-left', 'title' => 'Indent Text'],
						MarkdownEditor::BTN_INDENT_R => ['icon' => 'indent-right', 'title' => 'Unindent Text'],
					],
				],
				[
					'buttons' => [
						MarkdownEditor::BTN_UL => ['icon' => 'list', 'title' => 'Bulleted List'],
						MarkdownEditor::BTN_OL => ['icon' => 'list-alt', 'title' => 'Numbered List'],
					],
				],
				[
					'buttons' => [
						MarkdownEditor::BTN_QUOTE => ['icon' => 'comment', 'title' => 'Block Quote'],
					],
				],
				[
					'buttons' => [
						MarkdownEditor::BTN_CODE => ['label' => MarkdownEditor::ICON_CODE, 'title' => 'Inline Code', 'encodeLabel' => false],
						MarkdownEditor::BTN_CODE_BLOCK => ['icon' => 'sound-stereo', 'title' => 'Code Block'],
					],
				],
				[
					'buttons' => [
						MarkdownEditor::BTN_MAXIMIZE => ['icon' => 'fullscreen', 'title' => 'Toggle full screen', 'data-enabled' => true]
					],
					'options' => ['class' => 'pull-right']
				],
			],
			'footerMessage' => 'For format your input, see the ' . Html::a('Markdown Syntax', 'http://michelf.ca/projects/php-markdown/concepts/'),
			'showExport' => false,
		]); ?>

		<?= $form->field($model, 'startDate')->widget(DatePicker::className(), [
			'options' => ['placeholder' => 'Enter start date ...'],
			'pluginOptions' => [
				'autoclose'=>true,
				'format' => 'yyyy-mm-dd'
			]
		]) ?>
		
		<?= $form->field($model, 'endDate')->widget(DatePicker::className(), [
			'type' => DatePicker::TYPE_COMPONENT_APPEND,
			'options' => ['placeholder' => 'Enter end date ...'],
			'pluginOptions' => [
				'autoclose' => true,
				'format' => 'yyyy-mm-dd'
			]
		]) ?>
		
		<?php if ($projectBuildId == 0): ?>
			<?= $form->field($model, 'projectBuildId')->widget(Select2::className(), ['data' => $builds]) ?>
		<?php endif ?>
		
		<?php if ($assigneeId == 0): ?>
			<?= $form->field($model, 'assigneeId')->widget(Select2::className(), ['data' => $members]) ?>
		<?php endif ?>
		
		<?= $form->field($model, 'priorityId')->dropDownList(Priority::getArray()) ?>
		
		<?php if ($model->isNewRecord): ?>
		<?= $form->field($attachment, 'baseName')->widget(FileInput::className(), [
			'showUpload' => false,
			'showRemove' => false,
			'options' => [
				// 'multiple' => true,
			],
			'buttonOptions' => [
				'class' => 'btn btn-default',
			],
		]) ?>
		<?php endif ?>
	</div>
	
	<?php if ($model->typeId == TaskType::TYPE_TARGET): ?>
		<?= $this->render('_overtime', ['form' => $form, 'task' => $model]) ?>
	<?php endif ?>
	<div class="panel-footer clearfix">
		<div class="pull-right">
			<?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' =>'btn btn-default']) ?>
			&nbsp;
			<?php if ($model->isNewRecord): ?>
				<?= Html::a('Cancel', ['index', 'projectId' => $model->projectId, 'typeId' => $model->typeId]) ?>
			<?php else: ?>
				<?= Html::a('Cancel', ['view', 'id' => $model->id]) ?>
			<?php endif ?>
		</div>
	</div>
</div>

<?php ActiveForm::end(); ?>

frontend/views/task/create.php
<?php

/**
 * @var yii\web\View $this
 * @var common\models\Task $model
 * @var integer $projectBuildId
 * @var integer $assigneeId
 */

$this->title = $model->project->name;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['project/index']];
$this->params['breadcrumbs'][] = $this->title;

$header = 'Create ' . $model->type;
?>

<?= $this->render('_form', [
	'model' => $model,
	'projectBuildId' => $projectBuildId,
	'assigneeId' => $assigneeId,
	'header' => $header
]) ?>

frontend/views/task/index.php
<?php

use common\models\Priority;
use common\models\Task;
use common\models\TaskStatus;
use common\models\TaskType;
use common\models\search\TaskSearch;
use ez\helpers\DateTime;
use ez\widgets\LiveFilter;
use ez\widgets\Modal;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

/**
 * @var yii\web\View $this
 * @var yii\widgets\ActiveForm $form
 * @var common\models\Project $project
 * @var integer $typeId
 * @var string $filter
 * @var yii\data\ActiveDataProvider $dataProvider
 */

$this->title = $project->name;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['project/index']];
$this->params['breadcrumbs'][] = $this->title;

// Load Email action via AJAX
Modal::begin([
	'id' => 'task-email-modal',
	'clientOptions' => [
		'modal' => true,
		'autoOpen' => false,
	],
]);
Modal::end();
?>

<?= $this->render('//layouts/_navbar', ['project' => $project, 'controller' => 'task', 'typeId' => $typeId]) ?>

<div class="panel panel-default">
	<div class="panel-heading clearfix">
		<div class="row">
			<div class="col-md-2">
				<?= Html::a('New ' . TaskType::getName($typeId),  ['create', 'projectId' => $project->id, 'typeId' => $typeId], [
					'class' => 'btn btn-default'
				]) ?>
			</div>
			<div class="col-md-10">
				<?= $this->render('_filter', ['project' => $project, 'typeId' => $typeId, 'filter' => $filter]) ?>
				<div class="col-md-4 pull-right">
				<?=	LiveFilter::widget([
					'name' => 'filter',
					'selection' => '.grid-view tbody tr',
					'options' => [
						'placeholder' => 'Search...',
					]
				]);	?>
				</div>
			</div>
		</div>
	</div>
	<div class="panel-body">
		<?php /* Pjax::begin([]); */ ?>
		<?= GridView::widget([
			'dataProvider' => $dataProvider,
			'tableOptions' => [
				'class' => 'table table-hover',
			],
			'columns' => [
				['class' => 'yii\grid\SerialColumn'],

				[
					'attribute' => 'name',
					'format' => 'raw',
					'value' => function($model, $index, $widget) {
						//$name = $model->name;
						//if ($model->statusId == TaskStatus::STATUS_RESOLVED) {
						//	$name = '<strike>' . $name . '</strike>';
						//}
						return Html::a($model->name, ['task/view', 'id' => $model->id]);
					}
				],
				[
					'attribute' => 'statusId',
					'format' => 'raw',
					'value' => function($model, $index, $widget) {
						return Html::a(TaskStatus::getLabel($model->statusId), ['index',
							'projectId' => $model->project->id,
							'typeId' => $model->typeId,
							'statusId' => $model->statusId
						]);
					}
				],
				[
					'attribute' => 'priorityId',
					'format' => 'raw',
					'value' => function($model, $index, $widget) {
						return Html::a(Priority::getText($model->priorityId), ['index',
							'projectId' => $model->project->id,
							'typeId' => $model->typeId,
							'priorityId' => $model->priorityId
						]);
					}
				],
				[
					'attribute' => 'assigneeId',
					'format' => 'raw',
					'value' => function($model, $index, $widget) {
						return Html::a($model->assignee->name, ['index',
							'projectId' => $model->project->id,
							'typeId' => $model->typeId,
							'assigneeId' => $model->assigneeId
						]);
					}
				],
				[
					'attribute' => 'Build',
					'format' => 'raw',
					'value' => function($model, $index, $widget) {
						return Html::a($model->projectBuild->build->code, ['index',
							'projectId' => $model->project->id,
							'typeId' => $model->typeId,
							'projectBuildId' => $model->projectBuildId
						]);
					}
				],
				[
					'attribute' => 'endDate',
					'format' => 'raw',
					'value' => function($model, $index, $widget) {
						return Html::a(DateTime::niceShort($model->endDate), ['index',
							'projectId' => $model->project->id,
							'typeId' => $model->typeId,
							'endDate' => $model->endDate
						]);
					}
				],
				[
					'attribute' => 'updateTime',
					'value' => function($model, $index, $widget) {
						return DateTime::timeAgo($model->updateTime);
					}
				],
			],
		]); ?>
		<?php /* Pjax::end(); */ ?>
	</div>
	<div class="panel-footer clearfix">
		<?php
			$params = Yii::$app->getRequest()->getQueryParams();
			$action[] = 'mail';				// Can't use ArrayHelper::merge() method
			foreach ($params as $key => $value) {
				$action[$key] = $value;
			}
			
			echo Html::a('Email', $action, [
				'class' => 'btn btn-default pull-right', 'data-toggle' => 'modal', 'data-target' => '#task-email-modal'
			]);
		?>
	</div>
</div>