common/models/ProjectBuild.php
<?php

namespace common\models;

use Yii;
use yii\db\Query;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "ProjectBuild".
 *
 * @property integer $id
 * @property integer $projectId
 * @property integer $buildId
 * @property integer $feedback
 * @property integer $alignment
 * @property integer $gameplay
 * @property integer $interrupt
 * @property integer $igp
 * @property integer $sound
 * @property integer $iap
 * @property integer $igpLocalization
 * @property integer $localization
 * @property integer $wjiap
 * @property integer $mrc
 * @property integer $tns
 * @property integer $gc
 * @property integer $authorId
 * @property string $createTime
 * @property string $updateTime
 * 
 * @property Project $project
 * @property Build $build
 * @property ProjectAssignment[] $assignees
 * @property Member $author
 */
class ProjectBuild extends \yii\db\ActiveRecord
{
	private $_summary;
	
	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'ProjectBuild';
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['projectId', 'buildId', 'authorId'], 'required'],
			[
				['projectId', 'buildId', 'authorId',
					'feedback', 'alignment', 'gameplay',
					'interrupt', 'igp', 'sound', 'iap', 'igpLocalization',
					'localization', 'wjiap', 'mrc', 'tns', 'gc'
				],
				'integer'
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'projectId' => 'Project',
			'buildId' => 'Build',
			'authorId' => 'Added by',
			'createTime' => 'Create Time',
			'feedback' => 'FB',
			'alignment' => 'DA',
			'gameplay' => 'GP',
			'interrupt' => 'INT',
			'igp' => 'IGP',
			'sound' => 'SND',
			'iap' => 'IAP',
			'igpLocalization' => 'IGP LOC',
			'localization' => 'LOC',
			'wjiap' => 'WJIAP',
			'mrc' => 'MRC',
			'tns' => 'TNS',
			'gc' => 'GC',
			'createTime' => 'Create',
			'updateTime' => 'Update',
		];
	}
	
	/**
	 * Fill ProjectBuild.authorId before call validate.
	 * @inheritdoc
	 */
	public function beforeValidate()
	{
		if ($this->isNewRecord) {
			$this->authorId = Yii::$app->user->getId();
		}
		return parent::beforeValidate();
	}
	
	/**
	 * Get the Project model.
	 * @return \yii\db\ActiveRelation
	 */
	public function getProject()
	{
		return $this->hasOne(Project::className(), ['id' => 'projectId']);
	}
	
	/**
	 * Get the Build model.
	 * @return \yii\db\ActiveRelation
	 */
	public function getBuild()
	{
		return $this->hasOne(Build::className(), ['id' => 'buildId']);
	}
	
	/**
	 * Get the ProjectAssignment models.
	 * @return \yii\db\ActiveRelation
	 */
	public function getAssignees()
	{
		return $this->hasMany(ProjectAssignment::className(), ['projectBuildId' => 'id']);
	}
	
	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getAuthor()
	{
		return $this->hasOne(User::className(), ['id' => 'authorId']);
	}
	
	/**
	 * Count some relative info.
	 * @return mixed
	 */
	public function getSummary()
	{
		if ($this->_summary == null) {
			$this->_summary = [
				'unresolved-target' => Task::find()
					->where(['projectBuildId' => $this->id, 'typeId' => TaskType::TYPE_TARGET])
					->andWhere(['statusId' => [TaskStatus::STATUS_NEW, TaskStatus::STATUS_ON_HOLD, TaskStatus::STATUS_OPEN]])
					->count(),
				'unresolved-issue' => Task::find()
					->andWhere(['projectBuildId' => $this->id, 'typeId' => TaskType::TYPE_ISSUE])
					->andWhere(['statusId' => [TaskStatus::STATUS_NEW, TaskStatus::STATUS_ON_HOLD, TaskStatus::STATUS_OPEN]])
					->count(),
				'unresolved-feedback' => $count = Task::find()
					->andWhere(['projectBuildId' => $this->id, 'typeId' => TaskType::TYPE_FEEDBACK])
					->andWhere(['statusId' => [TaskStatus::STATUS_NEW, TaskStatus::STATUS_ON_HOLD, TaskStatus::STATUS_OPEN]])
					->count(),
				'unresolved-milestone' => Task::find()
					->andWhere(['projectBuildId' => $this->id, 'typeId' => TaskType::TYPE_MILESTONE])
					->andWhere(['statusId' => [TaskStatus::STATUS_NEW, TaskStatus::STATUS_ON_HOLD, TaskStatus::STATUS_OPEN]])
					->count(),
			];
		}
		
		return $this->_summary;
	}
	
	/**
	 * Check the record was exists.
	 * @return boolean
	 */
	public static function isExist($model)
	{
		$projectBuild = static::find()
			->where(['buildId' => $model->buildId])
			->andWhere(['projectId' => $model->projectId])
			->one();
		$isExist = ($projectBuild != null);
		
		return $isExist;
	}
	
	/**
	 * Get the user lists.
	 * @TODO should base on the roles.
	 */
	public static function getArrayByProjectId($projectId)
	{
		$builds = static::find()
			->with('build')
			->where(['projectId' => $projectId])
			->all();
		
		$builds = ArrayHelper::map($builds, 'id', 'build.name');
		return $builds;
	}
}

frontend/controllers/ProjectBuildController.php
<?php

namespace frontend\controllers;

use common\models\BuildStatus;
use common\models\Project;
use common\models\ProjectBuild;
use common\models\TaskStatus;
use common\models\TaskType;
use common\models\Role;
use common\models\search\ProjectBuildSearch;
use common\models\search\TaskSearch;
use yii\data\ActiveDataProvider;
use yii\web\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use Yii;

/**
 * ProjectBuildController implements the CRUD actions for ProjectBuild model.
 */
class ProjectBuildController extends Controller
{
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'actions' => ['index', 'view'],
						'roles' => ['@'],
					],
					[
						'allow' => true,
						'actions' => ['manage', 'create', 'update', 'delete'],
						'roles' => [Role::ROLE_MANAGER],
					],
				],
			],
		];
	}
	
	/**
	 * Displays all build assigments of a project.
	 * @param integer $projectId		project id, require.
	 * @return mixed
	 */
	public function actionIndex($projectId)
	{
		$searchModel = new ProjectBuildSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
		
		return $this->render('index', [
			'project' => Project::find($projectId),
			'dataProvider' => $dataProvider,
		]);
	}
	
	/**
	 * Displays all build assigments of a project, add update + delete.
	 * @param string $projectId project id
	 * @return mixed
	 */
	public function actionManage($projectId)
	{
		$searchModel = new ProjectBuildSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
		
		return $this->render('manage', [
			'project' => Project::find($projectId),
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	 * Displays a single ProjectBuild model.
	 * @param string $id
	 * @return mixed
	 */
	public function actionView($id, $feedback = null)
	{
		$model = $this->findModel($id);
		$searchModel = new TaskSearch();
		$targetProvider = $searchModel->search([
			'projectId' => $model->projectId,
			'projectBuildId' => $id,
			'typeId' => TaskType::TYPE_TARGET,
			'status' => TaskStatus::STATUS_UNRESOLVED
		]); 
		$feedbackProvider = $searchModel->search([
			'projectId' => $model->projectId,
			'projectBuildId' => $id,
			'typeId' => TaskType::TYPE_FEEDBACK,
			'status' => TaskStatus::STATUS_UNRESOLVED
		]); 
		$issueProvider = $searchModel->search([
			'projectId' => $model->projectId,
			'projectBuildId' => $id,
			'typeId' => TaskType::TYPE_ISSUE,
			'status' => TaskStatus::STATUS_UNRESOLVED
		]);
		
		return $this->render('view', [
			'model' => $model,
			'targetProvider' => $targetProvider,
			'feedbackProvider' => $feedbackProvider,
			'issueProvider' => $issueProvider,
		]);
	}

	/**
	 * Creates a new ProjectBuild model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate($projectId)
	{
		$builds = Yii::$app->getRequest()->post('builds');
		$count = 0;
		
		foreach ($builds as $build) {
			$model = new ProjectBuild();
			$model->projectId = $projectId;
			$model->buildId = $build;
			
			if (!ProjectBuild::isExist($model)) {
				// \yii\helpers\VarDumper::dump($model, 10, true); exit();
				$model->save();
				$count++;
			}
		}
		
		Yii::$app->session->setFlash('info', "Added {$count} build(s) successful.");
		return $this->redirect(['manage', 'projectId' => $projectId]);
	}
	
	/**
	 * Update a ProjectBuild model.
	 * @TODO AJAX action.
	 * @return mixed
	 */
	public function actionUpdate($id)
	{
		$model = $this->findModel($id);
		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			Yii::$app->session->setFlash('info', "Status updated.");
		}
		
		return $this->redirect(['view', 'id' => $id]);
	}
	
	/**
	 * Deletes an existing ProjectBuild model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param string $id
	 * @return mixed
	 */
	public function actionDelete($id)
	{
		// if (!Yii::$app->getRequest()->getIsAjax()) {
		$model = $this->findModel($id);
		if (Yii::$app->request->getIsPost()) {
			$model->delete();
			return $this->redirect(['manage', 'projectId' => $model->projectId]);
		} else {
			return $this->renderAjax('delete', ['model' => $model]);
		}
	}

	/**
	 * Finds the ProjectBuild model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param string $id
	 * @return ProjectBuild the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = ProjectBuild::find($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}
}

frontend/views/project-build/view/_change.php
<?php

use common\models\BuildStatus;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var common\models\ProjectBuild $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<?php
$status = BuildStatus::getArray();
?>

<?php $form = ActiveForm::begin([
	'id' => 'change-form',
	// 'enableAjaxValidation' => true,
	'action' =>['project-build/update', 'id' => $model->id],
]); ?>

<div class="modal fade" id="change-modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 id="change-modal-title">Change status</h4>
			</div>
			<div class="modal-body">
				<div class="row form-horizontal">
					<label class="col-lg-2 control-label">To</label>
					<div class="col-lg-10">
						<?= Html::dropDownList('change-attribute', 2, $status, [
							'id' => 'change-attribute',
							'class' => 'form-control'
						]) ?>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<?= Html::submitButton('Change', ['id' => 'change-submit', 'class' => 'btn btn-default']) ?>
				&nbsp;
				<?= Html::a('Cancel', '#', ['data-dismiss' => 'modal']) ?>
			</div>
		</div>
	</div>
</div>

<?php ActiveForm::end(); ?>

frontend/views/project-build/view/_info.php
<?php

use common\models\BuildStatus;
use common\models\TaskType;
use common\models\Role;
use ez\widgets\LiveFilter;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var common\models\ProjectBuild $model
 */
?>

<?php
$assignments = $model->assignees;
?>

<div class="panel panel-default">
	<div class="panel-heading clearfix">
		<strong><?= $model->build->name ?><span class="small"> <?= BuildStatus::getLabel($model->gc) ?></span></strong>
		<div class="col-md-4 pull-right">
			<?=	LiveFilter::widget([
				'name' => 'filter',
				'selection' => '.grid-view tbody tr',
				'options' => [
					'placeholder' => 'Search...',
				]
			]);	?>
		</div>
	</div>
	<div class="panel-body">
		<?php foreach ($assignments as $assignment): ?>
			<?= $assignment->projectMember->member->getAvatarImg(16, 16) ?>
			&nbsp;
			<?= Html::a($assignment->projectMember->member->name, '#') ?>
			<span class="text-muted small"><?= Role::getName($assignment->projectMember->member->role) ?></span>
			&nbsp;
		<?php endforeach ?>
		
		<ul>
			<li>
				<?= $model->summary['unresolved-target'] ?> unresolved targets
				<?= Html::a(' <span class="glyphicon glyphicon-plus small"></span>',
					[
						'task/create',
						'projectId' => $model->projectId,
						'typeId' => TaskType::TYPE_TARGET,
						'projectBuildId' => $model->id,
					],
					[
						'class' => 'tip',
						'data-toggle' => 'tooltip',
						'title' => 'Add target...'
					]
				) ?>
			</li>
			<li>
				<?= $model->summary['unresolved-issue'] ?> unresolved issues
				<?= Html::a(' <span class="glyphicon glyphicon-plus small"></span>',
					[
						'task/create',
						'projectId' => $model->projectId,
						'typeId' => TaskType::TYPE_ISSUE,
						'projectBuildId' => $model->id,
					],
					[
						'class' => 'tip',
						'data-toggle' => 'tooltip',
						'title' => 'Add issue...'
					]
				) ?>
			</li>
			<li>
				<?= $model->summary['unresolved-feedback'] ?> unresolved feedbacks
				<?= Html::a(' <span class="glyphicon glyphicon-plus small"></span>',
					[
						'task/create',
						'projectId' => $model->projectId,
						'typeId' => TaskType::TYPE_FEEDBACK,
						'projectBuildId' => $model->id,
					],
					[
						'class' => 'tip',
						'data-toggle' => 'tooltip',
						'title' => 'Add feedback...'
					]
				) ?>
			</li>
			<li>
				<?= $model->summary['unresolved-milestone'] ?> unresolved milestones
				<?= Html::a(' <span class="glyphicon glyphicon-plus small"></span>',
					[
						'task/create',
						'projectId' => $model->projectId,
						'typeId' => TaskType::TYPE_MILESTONE,
						'projectBuildId' => $model->id,
					],
					[
						'class' => 'tip',
						'data-toggle' => 'tooltip',
						'title' => 'Add milestone...'
					]
				) ?>
			</li>
		</ul>
	</div>
</div>

frontend/views/project-build/view/_status.php
<?php

use common\models\BuildStatus;
use ez\helpers\DateTime;
use yii\helpers\Html;
use yii\widgets\DetailView;

/**
 * @var yii\web\View $this
 * @var common\models\ProjectBuild $model
 */
?>

<?= $this->render('view/_change', ['model' => $model]) ?>

<div class="panel panel-default">
	<?= DetailView::widget([
		'model' => $model,
		'template' => "<tr class=\"row\">\n<td class=\"col-lg-8 text-right\">{label}</td>\n<td class=\"col-lg-4\">{value}</td>\n</tr>\n",
		'options' => [
			'class' => 'table table-hover small',
		],
		'attributes' => [
			[
				'label' => 'feedback',
				'format' => 'raw',
				'value' => Html::a(BuildStatus::getLabel($model->feedback), '#status', [
					'class' => 'build-change-status',
					'title' => 'Change feedback',
					'data-attribute' => 'feedback',
					'data-status' => $model->feedback
				])
			],
			[
				'label' => 'alignment',
				'format' => 'raw',
				'value' => Html::a(BuildStatus::getLabel($model->alignment), '#status', [
					'class' => 'build-change-status',
					'title' => 'Change alignment',
					'data-attribute' => 'alignment',
					'data-status' => $model->alignment
				])
			],
			[
				'label' => 'game-play',
				'format' => 'raw',
				'value' => Html::a(BuildStatus::getLabel($model->gameplay), '#status', [
					'class' => 'build-change-status',
					'title' => 'Change game-play',
					'data-attribute' => 'gameplay',
					'data-status' => $model->gameplay
				])
			],
			[
				'label' => 'interrupt',
				'format' => 'raw',
				'value' => Html::a(BuildStatus::getLabel($model->interrupt), '#status', [
					'class' => 'build-change-status',
					'title' => 'Change interrupt',
					'data-attribute' => 'interrupt',
					'data-status' => $model->interrupt
				])
			],
			[
				'name' => 'igp',
				'format' => 'raw',
				'value' => Html::a(BuildStatus::getLabel($model->igp), '#status', [
					'class' => 'build-change-status',
					'title' => 'Change igp',
					'data-attribute' => 'igp',
					'data-status' => $model->igp
				])
			],
			[
				'label' => 'sound',
				'format' => 'raw',
				'value' => Html::a(BuildStatus::getLabel($model->sound), '#status', [
					'class' => 'build-change-status',
					'title' => 'Change sound',
					'data-attribute' => 'sound',
					'data-status' => $model->sound
				])
			],
			[
				'name' => 'iap',
				'format' => 'raw',
				'value' => Html::a(BuildStatus::getLabel($model->iap), '#status', [
					'class' => 'build-change-status',
					'title' => 'Change IAP',
					'data-attribute' => 'iap',
					'data-status' => $model->iap
				])
			],
			[
				'label' => 'igp loc',
				'format' => 'raw',
				'value' => Html::a(BuildStatus::getLabel($model->igpLocalization), '#status', [
					'class' => 'build-change-status',
					'title' => 'Change IGP Localization',
					'data-attribute' => 'igpLocalization',
					'data-status' => $model->igpLocalization
				])
			],
			[
				'label' => 'localization',
				'format' => 'raw',
				'value' => Html::a(BuildStatus::getLabel($model->localization), '#status', [
					'class' => 'build-change-status',
					'title' => 'Change localization',
					'data-attribute' => 'localization',
					'data-status' => $model->localization
				])
			],
			[
				'name' => 'wjiap',
				'format' => 'raw',
				'value' => Html::a(BuildStatus::getLabel($model->wjiap), '#status', [
					'class' => 'build-change-status',
					'title' => 'Change WJIAP',
					'data-attribute' => 'wjiap',
					'data-status' => $model->wjiap
				])
			],
			[
				'name' => 'mrc',
				'format' => 'raw',
				'value' => Html::a(BuildStatus::getLabel($model->mrc), '#status', [
					'class' => 'build-change-status',
					'title' => 'Change MRC',
					'data-attribute' => 'mrc',
					'data-status' => $model->mrc
				])
			],
			[
				'name' => 'tns',
				'format' => 'raw',
				'value' => Html::a(BuildStatus::getLabel($model->tns), '#status', [
					'class' => 'build-change-status',
					'title' => 'Change TNS',
					'data-attribute' => 'tns',
					'data-status' => $model->tns
				])
			],
			[
				'label' => 'gold check',
				'format' => 'raw',
				'value' => Html::a(BuildStatus::getLabel($model->gc), '#status', [
					'class' => 'build-change-status',
					'title' => 'Change gold check',
					'data-attribute' => 'gc',
					'data-status' => $model->gc
				])
			],
		],
	]); ?>
</div>

frontend/views/project-build/view/_task.php
<?php

use common\models\BuildStatus;
use common\models\Priority;
use common\models\Role;
use common\models\TaskStatus;
use ez\helpers\DateTime;;
use yii\helpers\Html;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var common\models\ProjectBuild $model
* @var yii\data\ActiveDataProvider $dataProvider
 */
?>

<?= GridView::widget([
	'dataProvider' => $dataProvider,
	'tableOptions' => [
		'class' => 'table table-hover small',
	],
	'columns' => [
		['class' => 'yii\grid\SerialColumn'],

		[
			'attribute' => 'name',
			'format' => 'raw',
			'value' => function($model, $index, $widget) {
				$name = $model->name;
				return Html::a($name, ['task/view', 'id' => $model->id]);
			}
		],
		[
			'attribute' => 'statusId',
			'format' => 'raw',
			'value' => function($model, $index, $widget) {
				return ('<small>' . TaskStatus::getLabel($model->statusId) . '</small>');
			}
		],
		[
			'attribute' => 'priorityId',
			'format' => 'raw',
			'value' => function($model, $index, $widget) {
				return Priority::getText($model->priorityId);
			}
		],
		/* [
			'attribute' => 'authorId',
			'value' => function($model, $index, $widget) {
				return ($model->author->name);
			}
		], */
		[
			'attribute' => 'assigneeId',
			'value' => function($model, $index, $widget) {
				return $model->assignee->name;
			}
		],
		/* [
			'attribute' => 'createTime',
			'value' => function($model, $index, $widget) {
				return DateTime::timeAgo($model->createTime);
			}
		], */
		[
			'attribute' => 'updateTime',
			'value' => function($model, $index, $widget) {
				return DateTime::timeAgo($model->updateTime);
			}
		],
		[
			'attribute' => 'modifierId',
			'value' => function($model, $index, $widget) {
				return $model->modifier->name;
			}
		],
	],
]); ?>